#!/bin/sh

# Bootstrap for the install-homebrew devcontainer feature.
#
# This feature is FOUNDATIONAL — it cannot use the standard bootstrap pattern
# because it IS the prerequisite for that pattern on macOS.
#
# Responsibilities:
#   1. On macOS without a package manager: install Homebrew via curl.
#   2. Ensure bash >=4 is present; install it via the available package manager.
#   3. Exec scripts/install.sh under bash >=4 for all further work.
#
# Notes
# -----
# This file is NOT generated by sync-lib.sh — the .no-bootstrap-sync marker
# in this directory prevents it from being overwritten.
# Edit this file directly; it is the single source of truth for this feature's
# bootstrap.
#
# _lib/ is still synced by sync-lib.sh and is available to scripts/install.sh.

set -e

_SELF_DIR="$(dirname "$0")"

# Source the POSIX sh-compatible net module for fetch operations.
# shellcheck source=scripts/_lib/net.sh
. "$_SELF_DIR/scripts/_lib/net.sh"

# _find_bash4 — print the path to the first bash >=4 found; return 1 if none.
# Probes $PATH first, then well-known install prefixes so that a just-installed
# bash (e.g. Homebrew's /opt/homebrew/bin/bash) is discovered even in a shell
# session whose PATH has not yet been updated.
_find_bash4() {
    for _c in bash \
               /usr/local/bin/bash \
               /opt/homebrew/bin/bash \
               /opt/local/bin/bash \
               "$HOME/.nix-profile/bin/bash" \
               /nix/var/nix/profiles/default/bin/bash; do
        command -v "$_c" > /dev/null 2>&1 || continue
        _v=$("$_c" -c 'echo ${BASH_VERSINFO[0]}' 2>/dev/null) || continue
        [ "${_v:-0}" -ge 4 ] && { echo "$_c"; return 0; }
    done
    return 1
}

# _install_homebrew — install Homebrew via the official installer.
# Uses net::fetch_url_stdout which handles both curl and wget with retries.
_install_homebrew() {
    echo "🔍 Homebrew not found — installing Homebrew." >&2
    # NONINTERACTIVE=1 suppresses all prompts and sudo password requests.
    NONINTERACTIVE=1 /bin/bash -c "$(net::fetch_url_stdout https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "✅ Homebrew installed." >&2
    return 0
}

# ── Step 1: On macOS, ensure a package manager is present ─────────────────────
if [ "$(uname -s)" = "Darwin" ]; then
    if ! command -v brew > /dev/null 2>&1 && ! command -v port > /dev/null 2>&1; then
        _install_homebrew
    fi
fi

# ── Step 2: Ensure bash >=4 ───────────────────────────────────────────────────
if ! _find_bash4 > /dev/null; then
    echo "🔍 bash >=4 not found — installing via system package manager." >&2
    if command -v brew > /dev/null 2>&1; then
        brew install bash
    elif command -v port > /dev/null 2>&1; then
        port install bash
    elif command -v nix-env > /dev/null 2>&1; then
        nix-env -i bash
    elif command -v apk > /dev/null 2>&1; then
        apk add --no-cache bash
    elif command -v apt-get > /dev/null 2>&1; then
        apt-get update && apt-get install -y --no-install-recommends bash
    elif command -v dnf > /dev/null 2>&1; then
        dnf install -y bash
    elif command -v microdnf > /dev/null 2>&1; then
        microdnf install -y bash
    elif command -v yum > /dev/null 2>&1; then
        yum install -y bash
    elif command -v zypper > /dev/null 2>&1; then
        zypper --non-interactive install bash
    elif command -v pacman > /dev/null 2>&1; then
        pacman -S --noconfirm --needed bash
    else
        echo "⛔ No supported package manager found to install bash >=4." >&2
        exit 1
    fi
fi

_BASH4=$(_find_bash4) || {
    echo "⛔ bash >=4 still not found after installation attempt." >&2
    exit 1
}

exec "$_BASH4" "$_SELF_DIR/scripts/install.sh" "$@"
