#!/usr/bin/env bash
# test/run.sh — Unified test dispatcher.
#
# Usage:
#   bash test/run.sh unit    [--module <name>] [--filter <regex>] [--jobs <n>]
#   bash test/run.sh feature <feature>
#   bash test/run.sh macos   <feature> [--filter <scenario>]
#   bash test/run.sh dist    [--suite <build|get|sysset|macos>] [--filter <name>]
#   bash test/run.sh dry-run
#   bash test/run.sh all
#
# Exit code: 0 if all selected tests pass, 1 if any fail.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

_usage() {
  cat << 'EOF'
Usage: bash test/run.sh <subcommand> [options]

Subcommands:
  unit    [--module <name>] [--filter <regex>] [--jobs <n>]
  feature <feature>
  macos   <feature> [--filter <scenario>]
  dist    [--suite <build|get|sysset|macos>] [--filter <name>]
  dry-run
  all                        run unit, dry-run, and dist
EOF
}

if [[ $# -eq 0 ]]; then
  _usage >&2
  exit 1
fi

SUBCMD="$1"
shift

case "$SUBCMD" in
  unit)
    exec bash "${REPO_ROOT}/test/run-unit.sh" "$@"
    ;;
  feature)
    FEATURE="${1:?Usage: bash test/run.sh feature <feature>}"
    shift
    _rc=0
    devcontainer features test -f "$FEATURE" --skip-autogenerated \
      --project-folder "$REPO_ROOT" || _rc=$?
    bash "${REPO_ROOT}/test/run-fail-scenarios.sh" "$FEATURE" || _rc=$?
    exit "$_rc"
    ;;
  macos)
    exec bash "${REPO_ROOT}/test/run-macos.sh" "$@"
    ;;
  dist)
    exec bash "${REPO_ROOT}/test/dist/run.sh" "$@"
    ;;
  dry-run)
    exec bash "${REPO_ROOT}/test/install-os-pkg/dry-run/run.sh" "$@"
    ;;
  all)
    _rc=0
    bash "${REPO_ROOT}/test/run-unit.sh" || _rc=1
    bash "${REPO_ROOT}/test/install-os-pkg/dry-run/run.sh" || _rc=1
    bash "${REPO_ROOT}/test/dist/run.sh" || _rc=1
    exit "$_rc"
    ;;
  --help | -h)
    _usage
    exit 0
    ;;
  *)
    echo "⛔ Unknown subcommand: '$SUBCMD'" >&2
    _usage >&2
    exit 1
    ;;
esac
