#!/usr/bin/env bash
set -euo pipefail

_SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
_BASE_DIR="$(cd "$_SELF_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Debug / logging
# ---------------------------------------------------------------------------
if [ "${DEBUG:-false}" = "true" ]; then
  set -x
fi

# shellcheck source=lib/ospkg.sh
. "$_SELF_DIR/_lib/ospkg.sh"
# shellcheck source=lib/logging.sh
. "$_SELF_DIR/_lib/logging.sh"

logging__setup
trap 'logging__cleanup' EXIT

# ---------------------------------------------------------------------------
# 1. Install packages
# ---------------------------------------------------------------------------
ospkg__run --manifest "${_BASE_DIR}/dependencies/base.yaml"

# END OF AUTOGENERATED BLOCK

# shellcheck source=lib/users.sh
. "$_SELF_DIR/_lib/users.sh"

# ---------------------------------------------------------------------------
# 2. Ensure newuidmap / newgidmap have setuid bit
#
# The uidmap package ships these as setuid-root on Debian/Ubuntu.  Verify
# the bit is set — it is essential for rootless user-namespace creation.
# At runtime, privileged mode ensures nosuid is not applied.
# ---------------------------------------------------------------------------
chmod u+s /usr/bin/newuidmap /usr/bin/newgidmap 2> /dev/null || true

# ---------------------------------------------------------------------------
# 3. Resolve user list
# ---------------------------------------------------------------------------
mapfile -t _RESOLVED_USERS < <(users__resolve_list)

if [ ${#_RESOLVED_USERS[@]} -eq 0 ]; then
  echo "install-podman: No users to configure." >&2
fi

# ---------------------------------------------------------------------------
# 4. Write Podman configuration
#
# storage.conf (per-user): native overlay on the named volume at
# /var/lib/containers/storage.  Avoids both the overlay-on-overlay problem
# and fuse-overlayfs's nested-userns noexec issue.  Written to each user's
# config dir because rootless Podman ignores the system-level graphRoot.
# ---------------------------------------------------------------------------
# Write system-level containers.conf.
# These settings are only required when running Podman as root. Rootless
# Podman already defaults to cgroupfs and file, but root defaults to the
# systemd cgroup manager and journald — neither of which is available inside
# a Docker container.
# - cgroup_manager=cgroupfs: no systemd inside the container, so the default
#   systemd manager would fail with cgroup.subtree_control errors at runtime.
# - events_logger=file: journald is not available inside the container.
mkdir -p /etc/containers
printf '[engine]\ncgroup_manager = "cgroupfs"\nevents_logger = "file"\n' \
  > /etc/containers/containers.conf

GRAPH_ROOT="/var/lib/containers/storage"
mkdir -p "${GRAPH_ROOT}"

SUBUID_OFFSET=100000
for _username in "${_RESOLVED_USERS[@]}"; do
  if ! id "$_username" > /dev/null 2>&1; then
    echo "install-podman: User '${_username}' does not exist — skipping." >&2
    continue
  fi

  # Register subuid/subgid ranges (non-overlapping)
  if ! grep -q "^${_username}:" /etc/subuid 2> /dev/null; then
    echo "${_username}:${SUBUID_OFFSET}:65536" >> /etc/subuid
  fi
  if ! grep -q "^${_username}:" /etc/subgid 2> /dev/null; then
    echo "${_username}:${SUBUID_OFFSET}:65536" >> /etc/subgid
  fi
  SUBUID_OFFSET=$((SUBUID_OFFSET + 65536))

  # Write per-user storage.conf
  _home=$(eval echo "~${_username}")
  _config_dir="${_home}/.config/containers"
  mkdir -p "${_config_dir}"
  cat > "${_config_dir}/storage.conf" << EOF
[storage]
driver = "overlay"
graphRoot = "${GRAPH_ROOT}"
EOF

  # Fix ownership so Podman can write to config dirs at runtime
  chown -R "${_username}:$(id -gn "$_username")" "${_home}/.config"
done

# Ensure the graphRoot is accessible to all configured users.
# With privileged mode + user namespaces, broad permissions are safe.
chmod 1777 "${GRAPH_ROOT}"

# ---------------------------------------------------------------------------
# 5. Install entrypoint:
#    Mark "/" as rshared so bind-mount propagation
#    works inside rootless Podman's user namespace.
# ---------------------------------------------------------------------------
mkdir -p /usr/local/share/install-podman
printf '#!/bin/sh\nmount --make-rshared /\n' > /usr/local/share/install-podman/entrypoint
chmod +x /usr/local/share/install-podman/entrypoint
