#!/usr/bin/env bash
set -euo pipefail

_SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
_BASE_DIR="$(cd "$_SELF_DIR/.." && pwd)"

# shellcheck source=lib/ospkg.sh
. "$_SELF_DIR/_lib/ospkg.sh"
# shellcheck source=lib/logging.sh
. "$_SELF_DIR/_lib/logging.sh"
logging__setup
echo "↪️ Script entry: Rootless Podman" >&2
# Override _cleanup_hook in the hand-written section for feature-specific
# cleanup (e.g. removing temp files). Do NOT call logging__cleanup there;
# _on_exit owns that call and guarantees it runs exactly once, last.
# shellcheck disable=SC2329
_cleanup_hook() { return; }
# shellcheck disable=SC2329
_on_exit() {
  local _rc=$?
  _cleanup_hook
  if [[ $_rc -eq 0 ]]; then
    echo "✅ Rootless Podman script finished successfully." >&2
  else
    echo "❌ Rootless Podman script exited with error ${_rc}." >&2
  fi
  logging__cleanup
  return
}
trap '_on_exit' EXIT

__usage__() {
  cat << 'EOF'
Usage: install.sh [OPTIONS]

Options:
  --add_current_user {true,false}    Whether to configure Podman for the current non-root user (`SUDO_USER` if run via `sudo`, otherwise `whoami`). No effect when the current user is root. (default: "true")
  --add_remote_user {true,false}     Whether to configure Podman for the `_REMOTE_USER` set by the devcontainer tooling. No effect when running standalone. (default: "true")
  --add_container_user {true,false}  Whether to configure Podman for the `_CONTAINER_USER` set by the devcontainer tooling. No effect when running standalone. (default: "true")
  --add_users <value>  (repeatable)  Additional usernames to register subuid/subgid ranges and write Podman storage config for.
  --debug {true,false}               Enable debug output. (default: "false")
  --logfile <value>                  Log all output (stdout + stderr) to this file in addition to console.
  -h, --help                         Show this help
EOF
  return
}

if [ "$#" -gt 0 ]; then
  echo "ℹ️ Script called with arguments: $*" >&2
  ADD_CURRENT_USER=true
  ADD_REMOTE_USER=true
  ADD_CONTAINER_USER=true
  ADD_USERS=()
  DEBUG=false
  LOGFILE=""
  while [ "$#" -gt 0 ]; do
    case $1 in
      --add_current_user)
        shift
        ADD_CURRENT_USER="$1"
        echo "📩 Read argument 'add_current_user': '${ADD_CURRENT_USER}'" >&2
        shift
        ;;
      --add_remote_user)
        shift
        ADD_REMOTE_USER="$1"
        echo "📩 Read argument 'add_remote_user': '${ADD_REMOTE_USER}'" >&2
        shift
        ;;
      --add_container_user)
        shift
        ADD_CONTAINER_USER="$1"
        echo "📩 Read argument 'add_container_user': '${ADD_CONTAINER_USER}'" >&2
        shift
        ;;
      --add_users)
        shift
        ADD_USERS+=("$1")
        echo "📩 Read argument 'add_users': '$1'" >&2
        shift
        ;;
      --debug)
        shift
        DEBUG="$1"
        echo "📩 Read argument 'debug': '${DEBUG}'" >&2
        shift
        ;;
      --logfile)
        shift
        LOGFILE="$1"
        echo "📩 Read argument 'logfile': '${LOGFILE}'" >&2
        shift
        ;;
      -h | --help)
        __usage__
        exit 0
        ;;
      --*)
        echo "⛔ Unknown option: '${1}'" >&2
        exit 1
        ;;
      *)
        echo "⛔ Unexpected argument: '${1}'" >&2
        exit 1
        ;;
    esac
  done
else
  echo "ℹ️ Script called with no arguments. Read environment variables." >&2
  [ "${ADD_CURRENT_USER+defined}" ] && echo "📩 Read argument 'add_current_user': '${ADD_CURRENT_USER}'" >&2
  [ "${ADD_REMOTE_USER+defined}" ] && echo "📩 Read argument 'add_remote_user': '${ADD_REMOTE_USER}'" >&2
  [ "${ADD_CONTAINER_USER+defined}" ] && echo "📩 Read argument 'add_container_user': '${ADD_CONTAINER_USER}'" >&2
  if [ "${ADD_USERS+defined}" ]; then
    if [ -n "${ADD_USERS-}" ]; then
      mapfile -t ADD_USERS < <(printf '%s\n' "${ADD_USERS}" | grep -v '^$')
      for _item in "${ADD_USERS[@]}"; do
        echo "📩 Read argument 'add_users': '$_item'" >&2
      done
    else
      ADD_USERS=()
    fi
  fi
  [ "${DEBUG+defined}" ] && echo "📩 Read argument 'debug': '${DEBUG}'" >&2
  [ "${LOGFILE+defined}" ] && echo "📩 Read argument 'logfile': '${LOGFILE}'" >&2
fi

[[ "${DEBUG:-}" == true ]] && set -x

# Apply defaults.
[ "${ADD_CURRENT_USER+defined}" ] || ADD_CURRENT_USER=true
[ "${ADD_REMOTE_USER+defined}" ] || ADD_REMOTE_USER=true
[ "${ADD_CONTAINER_USER+defined}" ] || ADD_CONTAINER_USER=true
[ "${ADD_USERS+defined}" ] || ADD_USERS=()
[ "${DEBUG+defined}" ] || DEBUG=false
[ "${LOGFILE+defined}" ] || LOGFILE=""

ospkg__run --manifest "${_BASE_DIR}/dependencies/base.yaml" --skip_installed

# END OF AUTOGENERATED BLOCK

# shellcheck source=lib/users.sh
. "$_SELF_DIR/_lib/users.sh"

# ---------------------------------------------------------------------------
# 2. Ensure newuidmap / newgidmap have setuid bit
#
# The uidmap package ships these as setuid-root on Debian/Ubuntu.  Verify
# the bit is set — it is essential for rootless user-namespace creation.
# At runtime, privileged mode ensures nosuid is not applied.
# ---------------------------------------------------------------------------
chmod u+s /usr/bin/newuidmap /usr/bin/newgidmap 2> /dev/null || true

# ---------------------------------------------------------------------------
# 3. Resolve user list
# ---------------------------------------------------------------------------
mapfile -t _RESOLVED_USERS < <(users__resolve_list)

if [ ${#_RESOLVED_USERS[@]} -eq 0 ]; then
  echo "install-podman: No users to configure." >&2
fi

# ---------------------------------------------------------------------------
# 4. Write Podman configuration
#
# storage.conf (per-user): native overlay on the named volume at
# /var/lib/containers/storage.  Avoids both the overlay-on-overlay problem
# and fuse-overlayfs's nested-userns noexec issue.  Written to each user's
# config dir because rootless Podman ignores the system-level graphRoot.
# ---------------------------------------------------------------------------
# Write system-level containers.conf.
# These settings are only required when running Podman as root. Rootless
# Podman already defaults to cgroupfs and file, but root defaults to the
# systemd cgroup manager and journald — neither of which is available inside
# a Docker container.
# - cgroup_manager=cgroupfs: no systemd inside the container, so the default
#   systemd manager would fail with cgroup.subtree_control errors at runtime.
# - events_logger=file: journald is not available inside the container.
mkdir -p /etc/containers
printf '[engine]\ncgroup_manager = "cgroupfs"\nevents_logger = "file"\n' \
  > /etc/containers/containers.conf

GRAPH_ROOT="/var/lib/containers/storage"
mkdir -p "${GRAPH_ROOT}"

SUBUID_OFFSET=100000
for _username in "${_RESOLVED_USERS[@]}"; do
  if ! id "$_username" > /dev/null 2>&1; then
    echo "install-podman: User '${_username}' does not exist — skipping." >&2
    continue
  fi

  # Register subuid/subgid ranges (non-overlapping)
  if ! grep -q "^${_username}:" /etc/subuid 2> /dev/null; then
    echo "${_username}:${SUBUID_OFFSET}:65536" >> /etc/subuid
  fi
  if ! grep -q "^${_username}:" /etc/subgid 2> /dev/null; then
    echo "${_username}:${SUBUID_OFFSET}:65536" >> /etc/subgid
  fi
  SUBUID_OFFSET=$((SUBUID_OFFSET + 65536))

  # Write per-user storage.conf
  _home=$(eval echo "~${_username}")
  _config_dir="${_home}/.config/containers"
  mkdir -p "${_config_dir}"
  cat > "${_config_dir}/storage.conf" << EOF
[storage]
driver = "overlay"
graphRoot = "${GRAPH_ROOT}"
EOF

  # Fix ownership so Podman can write to config dirs at runtime
  chown -R "${_username}:$(id -gn "$_username")" "${_home}/.config"
done

# Ensure the graphRoot is accessible to all configured users.
# With privileged mode + user namespaces, broad permissions are safe.
chmod 1777 "${GRAPH_ROOT}"

# ---------------------------------------------------------------------------
# 5. Install entrypoint:
#    Mark "/" as rshared so bind-mount propagation
#    works inside rootless Podman's user namespace.
# ---------------------------------------------------------------------------
mkdir -p /usr/local/share/install-podman
printf '#!/bin/sh\nmount --make-rshared /\n' > /usr/local/share/install-podman/entrypoint
chmod +x /usr/local/share/install-podman/entrypoint
