# >>> setup-shell-zsh-zshrc-guard >>>
case $- in
  *i*) ;;
    *) return;;
esac
# <<< setup-shell-zsh-zshrc-guard <<<

# >>> setup-shell-zsh-zshrc-shellrc >>>
. "/etc/shellrc"
# <<< setup-shell-zsh-zshrc-shellrc <<<

# >>> setup-shell-zsh-zshrc-prompt >>>
PROMPT='%n@%m:%~%# '
# <<< setup-shell-zsh-zshrc-prompt <<<

# >>> setup-shell-zsh-zshrc-readnullcmd >>>
READNULLCMD=${PAGER:-/usr/bin/pager}
# <<< setup-shell-zsh-zshrc-readnullcmd <<<

# >>> setup-shell-zsh-zshrc-keybindings >>>
typeset -ga debian_missing_features
if [[ -z "${DEBIAN_PREVENT_KEYBOARD_CHANGES-}" ]] && [[ "$TERM" != 'emacs' ]]; then
  typeset -A key
  key=(
    BackSpace  "${terminfo[kbs]}"
    Home       "${terminfo[khome]}"
    End        "${terminfo[kend]}"
    Insert     "${terminfo[kich1]}"
    Delete     "${terminfo[kdch1]}"
    Up         "${terminfo[kcuu1]}"
    Down       "${terminfo[kcud1]}"
    Left       "${terminfo[kcub1]}"
    Right      "${terminfo[kcuf1]}"
    PageUp     "${terminfo[kpp]}"
    PageDown   "${terminfo[knp]}"
  )

  function bind2maps () {
    local i sequence widget
    local -a maps
    while [[ "$1" != "--" ]]; do
      maps+=( "$1" )
      shift
    done
    shift
    sequence="${key[$1]}"
    widget="$2"
    [[ -z "$sequence" ]] && return 1
    for i in "${maps[@]}"; do
      bindkey -M "$i" "$sequence" "$widget"
    done
  }

  bind2maps emacs             -- BackSpace   backward-delete-char
  bind2maps       viins       -- BackSpace   vi-backward-delete-char
  bind2maps             vicmd -- BackSpace   vi-backward-char
  bind2maps emacs             -- Home        beginning-of-line
  bind2maps       viins vicmd -- Home        vi-beginning-of-line
  bind2maps emacs             -- End         end-of-line
  bind2maps       viins vicmd -- End         vi-end-of-line
  bind2maps emacs viins       -- Insert      overwrite-mode
  bind2maps             vicmd -- Insert      vi-insert
  bind2maps emacs             -- Delete      delete-char
  bind2maps       viins vicmd -- Delete      vi-delete-char
  bind2maps emacs viins vicmd -- Up          up-line-or-search
  bind2maps emacs viins vicmd -- Down        down-line-or-search
  bind2maps emacs viins vicmd -- PageUp      history-beginning-search-backward
  bind2maps emacs viins vicmd -- PageDown    history-beginning-search-forward
  bind2maps emacs             -- Left        backward-char
  bind2maps       viins vicmd -- Left        vi-backward-char
  bind2maps emacs             -- Right       forward-char
  bind2maps       viins vicmd -- Right       vi-forward-char

  if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
    function zle-line-init () {
      emulate -L zsh
      printf '%s' ${terminfo[smkx]}
    }
    function zle-line-finish () {
      emulate -L zsh
      printf '%s' ${terminfo[rmkx]}
    }
    zle -N zle-line-init
    zle -N zle-line-finish
  else
    for i in {s,r}mkx; do
      (( ${+terminfo[$i]} )) || debian_missing_features+=($i)
    done
    unset i
  fi
  unfunction bind2maps
fi
# <<< setup-shell-zsh-zshrc-keybindings <<<

# >>> setup-shell-zsh-zshrc-zstyle >>>
zstyle ':completion:*:sudo:*' command-path \
    /usr/local/sbin \
    /usr/local/bin  \
    /usr/sbin       \
    /usr/bin        \
    /sbin           \
    /bin            \
    /usr/X11R6/bin

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
# <<< setup-shell-zsh-zshrc-zstyle <<<

# >>> setup-shell-zsh-zshrc-pre-compinit >>>
[ -f "/etc/zsh/shellcompletions" ] && . "/etc/zsh/shellcompletions"
# <<< setup-shell-zsh-zshrc-pre-compinit <<<

# >>> setup-shell-zsh-zshrc-compinit >>>
skip_global_compinit=1
autoload -Uz compinit
compinit
# <<< setup-shell-zsh-zshrc-compinit <<<

# >>> setup-shell-zsh-zshrc-run-help >>>
(( ${+aliases[run-help]} )) && unalias run-help
autoload -Uz run-help
# <<< setup-shell-zsh-zshrc-run-help <<<

# >>> setup-shell-zsh-zshrc-history >>>
bindkey -e
HISTSIZE=10000
SAVEHIST=5000
HISTFILE="$HOME/.zsh_history"
setopt histignorealldups
setopt sharehistory
setopt extended_history
setopt hist_ignore_space
# <<< setup-shell-zsh-zshrc-history <<<

# >>> setup-shell-zsh-zshrc-combining-chars >>>
if [[ "$(locale LC_CTYPE)" == "UTF-8" ]]; then
  setopt COMBINING_CHARS
fi
# <<< setup-shell-zsh-zshrc-combining-chars <<<

# >>> setup-shell-zsh-zshrc-term-program >>>
() {
  local _zshrc_dir="${${(%):-%x}:h}"
  [ -r "${_zshrc_dir}/zshrc_$TERM_PROGRAM" ] && . "${_zshrc_dir}/zshrc_$TERM_PROGRAM"
}
# <<< setup-shell-zsh-zshrc-term-program <<<

