#!/usr/bin/env bash
set -euo pipefail

_SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
_BASE_DIR="$(cd "$_SELF_DIR/.." && pwd)"

# shellcheck source=lib/ospkg.sh
. "$_SELF_DIR/_lib/ospkg.sh"
# shellcheck source=lib/logging.sh
. "$_SELF_DIR/_lib/logging.sh"
logging__setup
echo "↪️ Script entry: Shim Setup" >&2
# Override _cleanup_hook in the hand-written section for feature-specific
# cleanup (e.g. removing temp files). Do NOT call logging__cleanup there;
# _on_exit owns that call and guarantees it runs exactly once, last.
# shellcheck disable=SC2329
_cleanup_hook() { return; }
# shellcheck disable=SC2329
_on_exit() {
  local _rc=$?
  _cleanup_hook
  if [[ $_rc -eq 0 ]]; then
    echo "✅ Shim Setup script finished successfully." >&2
  else
    echo "❌ Shim Setup script exited with error ${_rc}." >&2
  fi
  logging__cleanup
  return
}
trap '_on_exit' EXIT

__usage__() {
  cat << 'EOF'
Usage: install.sh [OPTIONS]

Options:
  --code {true,false}               Install a `code` shim that delegates to the real `code` CLI or falls back to `code-insiders`. (default: "true")
  --devcontainer-info {true,false}  Install a `devcontainer-info` shim that queries dev container image metadata from meta.env files. (default: "true")
  --systemctl {true,false}          Install a `systemctl` shim that delegates to the real systemctl when systemd is running, or prints a helpful message suggesting the `service` command. (default: "true")
  --debug {true,false}              Enable debug output. (default: "false")
  --logfile <value>                 Log all output (stdout + stderr) to this file in addition to console.
  -h, --help                        Show this help
EOF
  return
}

if [ "$#" -gt 0 ]; then
  echo "ℹ️ Script called with arguments: $*" >&2
  CODE=true
  DEVCONTAINER_INFO=true
  SYSTEMCTL=true
  DEBUG=false
  LOGFILE=""
  while [ "$#" -gt 0 ]; do
    case $1 in
      --code)
        shift
        CODE="$1"
        echo "📩 Read argument 'code': '${CODE}'" >&2
        shift
        ;;
      --devcontainer-info)
        shift
        DEVCONTAINER_INFO="$1"
        echo "📩 Read argument 'devcontainer-info': '${DEVCONTAINER_INFO}'" >&2
        shift
        ;;
      --systemctl)
        shift
        SYSTEMCTL="$1"
        echo "📩 Read argument 'systemctl': '${SYSTEMCTL}'" >&2
        shift
        ;;
      --debug)
        shift
        DEBUG="$1"
        echo "📩 Read argument 'debug': '${DEBUG}'" >&2
        shift
        ;;
      --logfile)
        shift
        LOGFILE="$1"
        echo "📩 Read argument 'logfile': '${LOGFILE}'" >&2
        shift
        ;;
      -h | --help)
        __usage__
        exit 0
        ;;
      --*)
        echo "⛔ Unknown option: '${1}'" >&2
        exit 1
        ;;
      *)
        echo "⛔ Unexpected argument: '${1}'" >&2
        exit 1
        ;;
    esac
  done
else
  echo "ℹ️ Script called with no arguments. Read environment variables." >&2
  [ "${CODE+defined}" ] && echo "📩 Read argument 'code': '${CODE}'" >&2
  [ "${DEVCONTAINER_INFO+defined}" ] && echo "📩 Read argument 'devcontainer-info': '${DEVCONTAINER_INFO}'" >&2
  [ "${SYSTEMCTL+defined}" ] && echo "📩 Read argument 'systemctl': '${SYSTEMCTL}'" >&2
  [ "${DEBUG+defined}" ] && echo "📩 Read argument 'debug': '${DEBUG}'" >&2
  [ "${LOGFILE+defined}" ] && echo "📩 Read argument 'logfile': '${LOGFILE}'" >&2
fi

[[ "${DEBUG:-}" == true ]] && set -x

# Apply defaults.
[ "${CODE+defined}" ] || {
  CODE=true
  echo "ℹ️ Argument 'code' set to default value 'true'." >&2
}
[ "${DEVCONTAINER_INFO+defined}" ] || {
  DEVCONTAINER_INFO=true
  echo "ℹ️ Argument 'devcontainer-info' set to default value 'true'." >&2
}
[ "${SYSTEMCTL+defined}" ] || {
  SYSTEMCTL=true
  echo "ℹ️ Argument 'systemctl' set to default value 'true'." >&2
}
[ "${DEBUG+defined}" ] || {
  DEBUG=false
  echo "ℹ️ Argument 'debug' set to default value 'false'." >&2
}
[ "${LOGFILE+defined}" ] || {
  LOGFILE=""
  echo "ℹ️ Argument 'logfile' set to default value ''." >&2
}

# END OF AUTOGENERATED BLOCK

_SHIM_BIN="/usr/local/share/setup-shim/bin"
_FILES_DIR="${_BASE_DIR}/files"

# ---------------------------------------------------------------------------
# Install shims
# ---------------------------------------------------------------------------
mkdir -p "${_SHIM_BIN}"

install_shim() {
  _src="${_FILES_DIR}/$1"
  _dst="${_SHIM_BIN}/$1"
  if [ ! -f "$_src" ]; then
    echo "setup-shim: source file not found: ${_src}" >&2
    exit 1
  fi
  cp "$_src" "$_dst"
  chmod +rx "$_dst"
  echo "  ✅ $1 → ${_dst}"
  return
}

if [ "${CODE:-true}" = "true" ]; then
  install_shim "code"
fi

if [ "${DEVCONTAINER_INFO:-true}" = "true" ]; then
  install_shim "devcontainer-info"
fi

if [ "${SYSTEMCTL:-true}" = "true" ]; then
  install_shim "systemctl"
fi

exit 0
