#!/bin/bash
# The 'install-shell' feature has many options with no single sensible default
# test. All meaningful test coverage is provided by the scenario-based tests in
# scenarios.json
# CI runs these tests with --skip-autogenerated to bypass this script.

set -e

source dev-container-features-test-lib

reportResults
