#!/bin/bash
# The 'install-os-pkg' feature requires the 'dir' option, which has no default
# value. Autogenerated tests (which build the container with default option
# values) would therefore fail at image-build time. All meaningful test
# coverage is provided by the scenario-based tests in scenarios.json.
# CI runs these tests with --skip-autogenerated to bypass this script.

set -e

source dev-container-features-test-lib

reportResults
