#!/usr/bin/env python3
"""sync-argparse.py — Generates the full header of each feature's scripts/install.sh.

The generated content covers everything from the shebang (#!/usr/bin/env bash)
through the argument-parsing block and default-variable initialisation, and is
terminated by a single end marker:

    # END OF AUTOGENERATED BLOCK

Everything after that marker in the file is hand-written implementation code
and is never touched by this script.

Options with ``type: array`` in metadata.yaml are treated as bash arrays:
  * CLI branch:      --flag <value>  (repeatable; each invocation appends)
  * env-var branch:  newline-delimited string split into an array
  * Defaults:        empty array  ()

The ``type: array`` is serialised as ``type: string`` in devcontainer-feature.json
(handled by sync-metadata.py).

Usage:
  python3 scripts/sync-argparse.py           # update all install.sh files
  python3 scripts/sync-argparse.py --check   # exit non-zero if any block is stale
"""

import re
import sys
from pathlib import Path

import yaml

MARKER_END = "# END OF AUTOGENERATED BLOCK"

SCRIPT_DIR = Path(__file__).parent
SRC_DIR = SCRIPT_DIR.parent / "src"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def strip_markdown(text: str) -> str:
    """Strip markdown formatting for plain-text display in usage strings."""
    if not text:
        return text
    # [link text](url) → link text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # **bold** → bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    # *italic* → italic
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    return text.strip()


def first_sentence(text: str) -> str:
    """Return the first non-empty line of a description."""
    for line in text.splitlines():
        line = line.strip()
        if line:
            return line
    return text.strip()


def opt_to_var(key: str) -> str:
    """Convert an option key (snake_case or kebab-case) to UPPER_SNAKE_CASE var name."""
    return key.upper().replace("-", "_")


def opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def shell_val(default, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS (non-array types only)."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt.get("type", "string")
    enum = opt.get("enum", [])
    if typ == "boolean":
        return "{true,false}"
    if typ == "array":
        return "<value>  (repeatable)"
    if enum:
        return "{" + "|".join(str(v) for v in enum) + "}"
    return "<value>"


# ---------------------------------------------------------------------------
# Block generator
# ---------------------------------------------------------------------------


def generate_block(feature_name: str, options: dict) -> str:
    """Return the full generated content from shebang to END marker (inclusive).

    The returned string ends with ``# END OF AUTOGENERATED BLOCK\\n``.
    """
    lines: list[str] = []

    # ── shebang + strict mode ────────────────────────────────────────────────
    lines.append("#!/usr/bin/env bash")
    lines.append("set -euo pipefail")
    lines.append("")

    # ── path variables ───────────────────────────────────────────────────────
    lines.append('_SELF_DIR="$(cd "$(dirname "$0")" && pwd)"')
    lines.append('_BASE_DIR="$(cd "$_SELF_DIR/.." && pwd)"')
    lines.append("")

    # ── library sourcing ─────────────────────────────────────────────────────
    lines.append("# shellcheck source=lib/ospkg.sh")
    lines.append('. "$_SELF_DIR/_lib/ospkg.sh"')
    lines.append("# shellcheck source=lib/logging.sh")
    lines.append('. "$_SELF_DIR/_lib/logging.sh"')
    lines.append("logging__setup")
    lines.append(
        f'echo "\u21aa\ufe0f Script entry: {feature_name}" >&2'
    )
    lines.append("_on_exit() {")
    lines.append("  local _rc=$?")
    lines.append("  if [[ $_rc -eq 0 ]]; then")
    lines.append(
        f'    echo "\u2705 {feature_name} script finished successfully." >&2'
    )
    lines.append("  else")
    lines.append(
        f'    echo "\u274c {feature_name} script exited with error ${{_rc}}." >&2'
    )
    lines.append("  fi")
    lines.append("  logging__cleanup")
    lines.append("  return")
    lines.append("}")
    lines.append("trap '_on_exit' EXIT")
    lines.append("")

    # ── __usage__ ───────────────────────────────────────────────────────────
    entries: list[tuple[str, str, str]] = []
    for key, opt in options.items():
        flag_str = f"  {opt_to_flag(key)} {usage_type_hint(opt)}"
        typ = opt.get("type", "string")
        default = opt.get("default", "")
        if typ == "boolean":
            disp_default = "true" if default else "false"
        elif typ == "array":
            disp_default = ""
        else:
            disp_default = str(default) if default is not None else ""
        desc = first_sentence(strip_markdown(opt.get("description", "")))
        entries.append((flag_str, desc, disp_default))
    help_flag = "  -h, --help"
    col_width = max(
        (len(f) for f, _, _ in entries),
        default=len(help_flag),
    )
    col_width = max(col_width, len(help_flag))

    lines.append("__usage__() {")
    lines.append("  cat << 'EOF'")
    lines.append("Usage: install.sh [OPTIONS]")
    lines.append("")
    lines.append("Options:")
    for (flag_str, desc, disp_default), (_key, _opt) in zip(entries, options.items()):
        padding = " " * (col_width - len(flag_str) + 2)
        desc_field = desc
        if disp_default:
            desc_field = f'{desc} (default: "{disp_default}")'
        lines.append(f"{flag_str}{padding}{desc_field}")
    help_padding = " " * (col_width - len(help_flag) + 2)
    lines.append(f"{help_flag}{help_padding}Show this help")
    lines.append("EOF")
    lines.append("  return")
    lines.append("}")
    lines.append("")

    # ── CLI branch ───────────────────────────────────────────────────────────
    lines.append('if [ "$#" -gt 0 ]; then')
    lines.append('  echo "\u2139\ufe0f Script called with arguments: $*" >&2')
    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        if typ == "array":
            lines.append(f"  {vname}=()")
        else:
            rhs = shell_val(opt.get("default", ""), typ)
            lines.append(f"  {vname}={rhs}")
    lines.append('  while [ "$#" -gt 0 ]; do')
    lines.append("    case $1 in")
    for key, opt in options.items():
        vname = opt_to_var(key)
        flag = opt_to_flag(key)
        typ = opt.get("type", "string")
        lines.append(f"      {flag})")
        lines.append("        shift")
        if typ == "array":
            lines.append(f'        {vname}+=("$1")')
            lines.append(
                f'        echo "\U0001f4e9 Read argument \'{key}\': \'$1\'" >&2'
            )
        else:
            lines.append(f'        {vname}="$1"')
            lines.append(
                f'        echo "\U0001f4e9 Read argument \'{key}\': \'${{{vname}}}\'" >&2'
            )
        lines.append("        shift")
        lines.append("        ;;")
    lines.append("      -h | --help)")
    lines.append("        __usage__")
    lines.append("        exit 0")
    lines.append("        ;;")
    lines.append("      --*)")
    lines.append('        echo "\u26d4 Unknown option: \'${1}\'" >&2')
    lines.append('        exit 1')
    lines.append('        ;;')
    lines.append('      *)')
    lines.append('        echo "\u26d4 Unexpected argument: \'${1}\'" >&2')
    lines.append("        exit 1")
    lines.append("        ;;")
    lines.append("    esac")
    lines.append("  done")

    # ── env-var branch ───────────────────────────────────────────────────────
    lines.append("else")
    lines.append(
        '  echo "\u2139\ufe0f Script called with no arguments. Read environment variables." >&2'
    )
    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        if typ == "array":
            lines.append(f"  if [ \"${{{vname}+defined}}\" ]; then")
            lines.append(f"    if [ -n \"${{{vname}-}}\" ]; then")
            lines.append(
                f'      mapfile -t {vname} < <(printf \'%s\\n\' "${{{vname}}}" | grep -v \'^$\')'
            )
            lines.append(f'      for _item in "${{{vname}[@]}}"; do')
            lines.append(
                f'        echo "\U0001f4e9 Read argument \'{key}\': \'$_item\'" >&2'
            )
            lines.append("      done")
            lines.append("    else")
            lines.append(f"      {vname}=()")
            lines.append("    fi")
            lines.append("  fi")
        else:
            lines.append(
                f'  [ "${{{vname}+defined}}" ] && echo "\U0001f4e9 Read argument \'{key}\': \'${{{vname}}}\'" >&2'
            )
    lines.append("fi")
    lines.append("")

    # ── set -x ───────────────────────────────────────────────────────────────
    lines.append('[[ "${DEBUG:-}" == true ]] && set -x')
    lines.append("")

    # ── defaults ─────────────────────────────────────────────────────────────
    lines.append("# Apply defaults.")
    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        if typ == "array":
            raw_default = opt.get("default", "")
            if raw_default == "" or raw_default is None:
                lines.append(f'[ "${{{vname}+defined}}" ] || {vname}=()')
            else:
                # Embed the default as an ANSI-C quoted string so newlines are preserved.
                escaped = (
                    str(raw_default)
                    .replace("\\", "\\\\")
                    .replace("'", "\\'")
                    .replace("\n", "\\n")
                    .replace("\r", "\\r")
                )
                lines.append(
                    f'[ "${{{vname}+defined}}" ] || '
                    f"mapfile -t {vname} < <(printf '%s' $'{escaped}' | grep -v '^$')"
                )
        else:
            rhs = shell_val(opt.get("default", ""), typ)
            lines.append(f'[ "${{{vname}+defined}}" ] || {vname}={rhs}')

    # ── end marker ────────────────────────────────────────────────────────────
    lines.append("")
    lines.append(MARKER_END)

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# File update
# ---------------------------------------------------------------------------


def replace_block(script_path: Path, new_block: str) -> tuple[bool, str]:
    """Replace from the start of the file to (and including) the MARKER_END line.

    Returns (changed, error_message). *error_message* is empty on success.
    """
    text = script_path.read_text(encoding="utf-8")

    end_pat = re.compile(r"^# END OF AUTOGENERATED BLOCK$", re.MULTILINE)
    m_end = end_pat.search(text)

    if m_end is None:
        return False, (
            f"marker '{MARKER_END}' not found in {script_path}\n"
            "  Add the marker after the existing argparse/defaults section, then re-run."
        )

    # new_block ends with "# END OF AUTOGENERATED BLOCK\n".
    # text[m_end.end():] starts with "\n" (the newline after the marker line).
    # Preserve exactly one blank line between the marker and the hand-written rest.
    rest = text[m_end.end():].lstrip("\n")
    new_text = new_block + ("\n" + rest if rest else "")

    if new_text == text:
        return False, ""
    script_path.write_text(new_text, encoding="utf-8")
    return True, ""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    check_mode = "--check" in sys.argv

    feature_dirs = sorted(SRC_DIR.glob("*/metadata.yaml"))
    if not feature_dirs:
        print(f"⛔ No metadata.yaml files found under {SRC_DIR}", file=sys.stderr)
        return 1

    any_stale = False
    any_error = False

    for meta_path in feature_dirs:
        feature_dir = meta_path.parent
        feature_id = feature_dir.name
        script_path = feature_dir / "scripts" / "install.sh"

        if not script_path.exists():
            continue

        with meta_path.open(encoding="utf-8") as fh:
            meta = yaml.safe_load(fh)

        feature_name: str = meta.get("name", feature_id)
        options: dict = meta.get("options", {})
        if not isinstance(options, dict):
            options = {}

        new_block = generate_block(feature_name, options)

        if check_mode:
            text = script_path.read_text(encoding="utf-8")
            end_pat = re.compile(r"^# END OF AUTOGENERATED BLOCK$", re.MULTILINE)
            m_end = end_pat.search(text)
            if m_end is None:
                print(
                    f"⛔ {feature_id}: '{MARKER_END}' marker missing",
                    file=sys.stderr,
                )
                any_stale = True
                continue
            # Compare from file start to end of marker line (including its \n)
            current_block = text[: m_end.end() + 1]
            if current_block != new_block:
                print(f"⛔ {feature_id}: generated header is stale", file=sys.stderr)
                any_stale = True
            else:
                print(f"✅ {feature_id}: in sync", file=sys.stderr)
        else:
            changed, err = replace_block(script_path, new_block)
            if err:
                print(f"⛔ {feature_id}: {err}", file=sys.stderr)
                any_error = True
            elif changed:
                print(f"✅ {feature_id}: header updated", file=sys.stderr)
            else:
                print(f"✅ {feature_id}: header unchanged", file=sys.stderr)

    if check_mode and any_stale:
        print("", file=sys.stderr)
        print(
            "⛔ Stale generated headers detected. Run: bash sync-lib.sh",
            file=sys.stderr,
        )
        return 1

    if any_error:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
