#!/usr/bin/env python3
"""
sync-argparse.py — Generates the dual-mode argument-parsing block in each
feature's scripts/install.sh from the feature's metadata.yaml.

The generated content is written between:
  # BEGIN_ARGPARSE
  # END_ARGPARSE
markers.  Features with ``x_custom_argparse: true`` in metadata.yaml are
skipped (their install.sh keeps a hand-written argparse block).

Usage:
  python3 scripts/sync-argparse.py           # update all install.sh files
  python3 scripts/sync-argparse.py --check   # exit non-zero if any block is stale
"""

import re
import sys
from pathlib import Path

import yaml

MARKER_BEGIN = "# BEGIN_ARGPARSE"
MARKER_END = "# END_ARGPARSE"
MARKER_BEGIN_FULL = (
    "# BEGIN_ARGPARSE"
    " -- do not edit; regenerated by sync-lib.sh from metadata.yaml"
)

SCRIPT_DIR = Path(__file__).parent
SRC_DIR = SCRIPT_DIR.parent / "src"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def strip_markdown(text: str) -> str:
    """Strip markdown formatting for plain-text display in usage strings."""
    if not text:
        return text
    # [link text](url) → link text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # **bold** → bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    # *italic* → italic
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    # `code` → keep as-is (readable in terminal)
    return text.strip()


def first_sentence(text: str) -> str:
    """Return the first sentence/line of a description."""
    # Take the first non-empty line
    for line in text.splitlines():
        line = line.strip()
        if line:
            return line
    return text.strip()


def opt_to_var(key: str) -> str:
    """Convert an option key (snake_case or kebab-case) to UPPER_SNAKE_CASE var name."""
    return key.upper().replace("-", "_")


def opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def shell_val(default, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt.get("type", "string")
    enum = opt.get("enum", [])
    if typ == "boolean":
        return "{true,false}"
    if enum:
        return "{" + "|".join(str(v) for v in enum) + "}"
    return "<string>"


# ---------------------------------------------------------------------------
# Block generator
# ---------------------------------------------------------------------------


def generate_block(options: dict) -> str:
    """Return the full generated argparse block (between and including markers)."""
    lines: list[str] = []

    # ── marker ──────────────────────────────────────────────────────────────
    lines.append(MARKER_BEGIN_FULL)
    lines.append("")

    # ── __usage__ ───────────────────────────────────────────────────────────
    # Compute column width for alignment
    entries: list[tuple[str, str]] = []
    for key, opt in options.items():
        flag_str = f"  {opt_to_flag(key)} {usage_type_hint(opt)}"
        default = opt.get("default", "")
        typ = opt.get("type", "string")
        if typ == "boolean":
            disp_default = "true" if default else "false"
        else:
            disp_default = str(default) if default is not None else ""
        desc = first_sentence(strip_markdown(opt.get("description", "")))
        entries.append((flag_str, desc, disp_default))
    help_flag = "  -h, --help"
    col_width = max(
        (len(f) for f, _, _ in entries),
        default=len(help_flag),
    )
    col_width = max(col_width, len(help_flag))

    lines.append("__usage__() {")
    lines.append("  cat << 'EOF'")
    lines.append("Usage: install.sh [OPTIONS]")
    lines.append("")
    lines.append("Options:")
    for (flag_str, desc, disp_default), (key, opt) in zip(entries, options.items()):
        padding = " " * (col_width - len(flag_str) + 2)
        desc_field = desc
        if disp_default:
            desc_field = f'{desc} (default: "{disp_default}")'
        lines.append(f"{flag_str}{padding}{desc_field}")
    # help entry
    help_padding = " " * (col_width - len(help_flag) + 2)
    lines.append(f"{help_flag}{help_padding}Show this help")
    lines.append("EOF")
    lines.append("  return")
    lines.append("}")
    lines.append("")

    # ── CLI branch ───────────────────────────────────────────────────────────
    lines.append('if [ "$#" -gt 0 ]; then')
    lines.append('  echo "ℹ️ Script called with arguments: $*" >&2')
    # Initialise each variable to its default value
    for key, opt in options.items():
        vname = opt_to_var(key)
        rhs = shell_val(opt.get("default", ""), opt.get("type", "string"))
        lines.append(f"  {vname}={rhs}")
    lines.append('  while [ "$#" -gt 0 ]; do')
    lines.append("    case $1 in")
    for key in options:
        vname = opt_to_var(key)
        flag = opt_to_flag(key)
        lines.append(f"      {flag})")
        lines.append("        shift")
        lines.append(f'        {vname}="$1"')
        lines.append(f'        echo "📩 Read argument \'{key}\': \'${{{vname}}}\'" >&2')
        lines.append("        shift")
        lines.append("        ;;")
    lines.append("      -h | --help)")
    lines.append("        __usage__")
    lines.append("        exit 0")
    lines.append("        ;;")
    lines.append("      --*)")
    lines.append('        echo "⛔ Unknown option: \'${1}\'" >&2')
    lines.append("        exit 1")
    lines.append("        ;;")
    lines.append("      *)")
    lines.append('        echo "⛔ Unexpected argument: \'${1}\'" >&2')
    lines.append("        exit 1")
    lines.append("        ;;")
    lines.append("    esac")
    lines.append("  done")

    # ── env-var branch ───────────────────────────────────────────────────────
    lines.append("else")
    lines.append(
        '  echo "ℹ️ Script called with no arguments. Read environment variables." >&2'
    )
    for key in options:
        vname = opt_to_var(key)
        lines.append(
            f'  [ "${{{vname}+defined}}" ] && echo "📩 Read argument \'{key}\': \'${{{vname}}}\'" >&2'
        )
    lines.append("fi")
    lines.append("")

    # ── set -x ───────────────────────────────────────────────────────────────
    lines.append('[[ "${DEBUG:-}" == true ]] && set -x')
    lines.append("")

    # ── defaults ─────────────────────────────────────────────────────────────
    lines.append("# Apply defaults.")
    for key, opt in options.items():
        vname = opt_to_var(key)
        rhs = shell_val(opt.get("default", ""), opt.get("type", "string"))
        lines.append(f'[ "${{{vname}+defined}}" ] || {vname}={rhs}')

    # ── end marker ────────────────────────────────────────────────────────────
    lines.append(MARKER_END)
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File update
# ---------------------------------------------------------------------------


def replace_block(script_path: Path, new_block: str) -> tuple[bool, str]:
    """
    Replace the content between BEGIN_ARGPARSE and END_ARGPARSE markers in
    *script_path* with *new_block*.  Returns (changed, error_message).
    *error_message* is empty on success.
    """
    text = script_path.read_text(encoding="utf-8")

    begin_pat = re.compile(r"^# BEGIN_ARGPARSE.*$", re.MULTILINE)
    end_pat = re.compile(r"^# END_ARGPARSE$", re.MULTILINE)

    m_begin = begin_pat.search(text)
    m_end = end_pat.search(text)

    if m_begin is None or m_end is None:
        return False, f"markers not found in {script_path}"
    if m_begin.start() >= m_end.start():
        return False, f"markers are in wrong order in {script_path}"

    # Include both marker lines in the replacement region
    region_start = m_begin.start()
    region_end = m_end.end()

    # Preserve trailing newline behaviour: new_block already ends with "\n"
    new_text = text[:region_start] + new_block + text[region_end + 1:]
    if new_text == text:
        return False, ""  # unchanged
    script_path.write_text(new_text, encoding="utf-8")
    return True, ""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    check_mode = "--check" in sys.argv

    feature_dirs = sorted(SRC_DIR.glob("*/metadata.yaml"))
    if not feature_dirs:
        print(f"⛔ No metadata.yaml files found under {SRC_DIR}", file=sys.stderr)
        return 1

    any_stale = False
    any_error = False

    for meta_path in feature_dirs:
        feature_dir = meta_path.parent
        feature_name = feature_dir.name
        script_path = feature_dir / "scripts" / "install.sh"

        if not script_path.exists():
            continue

        with meta_path.open(encoding="utf-8") as fh:
            meta = yaml.safe_load(fh)

        # Skip features that declare custom argparse
        if meta.get("x_custom_argparse", False):
            if check_mode:
                print(f"⏩ {feature_name}: custom argparse — skipping", file=sys.stderr)
            continue

        options: dict = meta.get("options", {})
        if not isinstance(options, dict):
            options = {}

        new_block = generate_block(options)

        if check_mode:
            text = script_path.read_text(encoding="utf-8")
            begin_pat = re.compile(r"^# BEGIN_ARGPARSE.*$", re.MULTILINE)
            end_pat = re.compile(r"^# END_ARGPARSE$", re.MULTILINE)
            m_begin = begin_pat.search(text)
            m_end = end_pat.search(text)
            if m_begin is None or m_end is None:
                print(
                    f"⛔ {feature_name}: BEGIN_ARGPARSE/END_ARGPARSE markers missing",
                    file=sys.stderr,
                )
                any_stale = True
                continue
            current_block = text[m_begin.start() : m_end.end()]
            expected_block = new_block.rstrip("\n")
            if current_block != expected_block:
                print(f"⛔ {feature_name}: argparse block is stale", file=sys.stderr)
                any_stale = True
            else:
                print(f"✅ {feature_name}: in sync", file=sys.stderr)
        else:
            changed, err = replace_block(script_path, new_block)
            if err:
                print(f"⛔ {feature_name}: {err}", file=sys.stderr)
                any_error = True
            elif changed:
                print(f"✅ {feature_name}: argparse block updated", file=sys.stderr)
            else:
                print(f"✅ {feature_name}: argparse block unchanged", file=sys.stderr)

    if check_mode and any_stale:
        print("", file=sys.stderr)
        print(
            "⛔ Stale argparse blocks detected. Run: bash sync-lib.sh",
            file=sys.stderr,
        )
        return 1

    if any_error:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
