#!/usr/bin/env python3
"""sync-argparse.py — Generates the full header of each feature's install.bash.

The generated content covers everything from the shebang (#!/usr/bin/env bash)
through the argument-parsing block and default-variable initialisation, and is
terminated by a single end marker:

    # END OF AUTOGENERATED BLOCK

Everything after that marker in the file is hand-written implementation code
and is never touched by this script.

Options with ``type: array`` in metadata.yaml are treated as bash arrays:
  * CLI branch:      --flag <value>  (repeatable; each invocation appends)
  * env-var branch:  newline-delimited string split into an array
  * Defaults:        empty array  ()

The ``type: array`` is serialised as ``type: string`` in devcontainer-feature.json
(handled by sync-metadata.py).

Usage:
  python3 scripts/sync-argparse.py           # update all install.bash files
  python3 scripts/sync-argparse.py --check   # exit non-zero if any block is stale
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

MARKER_END = "# END OF AUTOGENERATED BLOCK"

SCRIPT_DIR = Path(__file__).parent
FEATURES_DIR = SCRIPT_DIR.parent / "features"
SRC_DIR = SCRIPT_DIR.parent / "src"

# ---------------------------------------------------------------------------
# Derived (synthetic) options — loaded from shared YAML
# ---------------------------------------------------------------------------

_DERIVED_OPTIONS_PATH = SCRIPT_DIR / "derived-options.yaml"
with _DERIVED_OPTIONS_PATH.open(encoding="utf-8") as _fh:
    _DERIVED_OPTIONS: dict = yaml.safe_load(_fh)

# All keys that the generators manage (strip from raw metadata before re-injecting).
_DERIVED_OPTION_KEYS: frozenset[str] = frozenset(_DERIVED_OPTIONS)


def _synthetic(key: str) -> dict:
    """Return the option schema for a derived key, stripping the 'inject' meta-field."""
    return {k: v for k, v in _DERIVED_OPTIONS[key].items() if k != "inject"}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def strip_markdown(text: str) -> str:
    """Strip markdown formatting for plain-text display in usage strings."""
    if not text:
        return text
    # [link text](url) → link text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # **bold** → bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    # *italic* → italic
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    return text.strip()


def first_sentence(text: str) -> str:
    """Return the first non-empty line of a description."""
    for line in text.splitlines():
        line = line.strip()
        if line:
            return line
    return text.strip()


def opt_to_var(key: str) -> str:
    """Convert an option key (snake_case or kebab-case) to UPPER_SNAKE_CASE var name."""
    return key.upper().replace("-", "_")


def opt_to_flag(key: str) -> str:
    """Convert an option key to its --flag form."""
    return f"--{key}"


def shell_val(default, typ: str) -> str:
    """Format a YAML default value as a shell assignment RHS (non-array types only)."""
    if typ == "boolean":
        return "true" if default else "false"
    if default == "" or default is None:
        return '""'
    return f'"{default}"'


def usage_type_hint(opt: dict) -> str:
    """Return a concise type hint for the --help usage line."""
    typ = opt.get("type", "string")
    enum = opt.get("enum", [])
    if typ == "boolean":
        return "{true,false}"
    if typ == "array":
        return "<value>  (repeatable)"
    if enum:
        return "{" + "|".join(str(v) for v in enum) + "}"
    return "<value>"


# ---------------------------------------------------------------------------
# Block generator
# ---------------------------------------------------------------------------


def generate_block(feature_name: str, options: dict, dependencies: dict | None = None) -> str:
    """Return the full generated content from shebang to END marker (inclusive).

    The returned string ends with ``# END OF AUTOGENERATED BLOCK\n``.
    If *dependencies* contains a ``base`` key, an ``ospkg__run`` call is
    emitted as the last statement before the end marker.
    """
    # ── Derive has_ospkg and build the final options dict ────────────────────
    # has_ospkg is true when the metadata has a `dependencies` key (even empty),
    # which signals that this feature uses ospkg for package management.
    has_ospkg: bool = dependencies is not None

    # Strip derived keys that will be re-injected as synthetics.
    # keep_cache is only stripped when has_ospkg (it will be re-injected);
    # for features without ospkg, keep_cache may be a legitimate declared option.
    always_strip = _DERIVED_OPTION_KEYS - {"keep_cache"}
    keys_to_strip = always_strip | ({"keep_cache"} if has_ospkg else set())
    core_options: dict = {
        k: v for k, v in options.items() if k not in keys_to_strip
    }
    final_options: dict = dict(core_options)
    if has_ospkg:
        final_options["keep_cache"] = _synthetic("keep_cache")
    final_options["debug"] = _synthetic("debug")
    final_options["logfile"] = _synthetic("logfile")

    # All code generation below uses final_options (not the raw options dict).
    options = final_options

    lines: list[str] = []

    # ── shebang + strict mode ────────────────────────────────────────────────
    lines.append("#!/usr/bin/env bash")
    lines.append("set -euo pipefail")
    lines.append("")

    # ── path variables ───────────────────────────────────────────────────────
    lines.append('_SELF_DIR="$(cd "$(dirname "$0")" && pwd)"')
    lines.append('_BASE_DIR="$_SELF_DIR"')
    lines.append("")

    # ── library sourcing ─────────────────────────────────────────────────────
    lines.append("# shellcheck source=lib/ospkg.sh")
    lines.append('. "$_SELF_DIR/_lib/ospkg.sh"')
    lines.append("# shellcheck source=lib/logging.sh")
    lines.append('. "$_SELF_DIR/_lib/logging.sh"')
    lines.append("logging__setup")
    lines.append(
        f'echo "\u21aa\ufe0f Script entry: {feature_name}" >&2'
    )
    lines.append("# Override _cleanup_hook in the hand-written section for feature-specific")
    lines.append("# cleanup (e.g. removing temp files). Do NOT call logging__cleanup there;")
    lines.append("# _on_exit owns that call and guarantees it runs exactly once, last.")
    lines.append("# shellcheck disable=SC2329,SC2317")
    lines.append("_cleanup_hook() { return; }")
    lines.append("# shellcheck disable=SC2329,SC2317")
    lines.append("_on_exit() {")
    lines.append("  local _rc=$?")
    lines.append("  _cleanup_hook")
    if has_ospkg:
        lines.append('  [[ "${KEEP_CACHE:-true}" != true ]] && ospkg__clean')
    lines.append("  if [[ $_rc -eq 0 ]]; then")
    lines.append(
        f'    echo "\u2705 {feature_name} script finished successfully." >&2'
    )
    lines.append("  else")
    lines.append(
        f'    echo "\u274c {feature_name} script exited with error ${{_rc}}." >&2'
    )
    lines.append("  fi")
    lines.append("  logging__cleanup")
    lines.append("  return")
    lines.append("}")
    lines.append("trap '_on_exit' EXIT")
    lines.append("")

    # ── __usage__ ───────────────────────────────────────────────────────────
    entries: list[tuple[str, str, str, bool]] = []
    for key, opt in options.items():
        typ = opt["type"]
        flag_str = f"  {opt_to_flag(key)} {usage_type_hint(opt)}"
        has_default = "default" in opt
        default = opt.get("default", "")
        is_required = not has_default
        if typ == "boolean":
            disp_default = "true" if default else "false"
        elif typ == "array":
            disp_default = ""
        else:
            disp_default = str(default) if has_default and default is not None else ""
        desc = first_sentence(strip_markdown(opt.get("description", "")))
        entries.append((flag_str, desc, disp_default, is_required))
    help_flag = "  -h, --help"
    col_width = max(
        (len(f) for f, _, _, _ in entries),
        default=len(help_flag),
    )
    col_width = max(col_width, len(help_flag))

    lines.append("__usage__() {")
    lines.append("  cat << 'EOF'")
    lines.append("Usage: install.bash [OPTIONS]")
    lines.append("")
    lines.append("Options:")
    for (flag_str, desc, disp_default, is_required), (_key, _opt) in zip(entries, options.items()):
        padding = " " * (col_width - len(flag_str) + 2)
        desc_field = desc
        if is_required:
            desc_field = f"{desc} (required)"
        elif disp_default:
            desc_field = f'{desc} (default: "{disp_default}")'
        lines.append(f"{flag_str}{padding}{desc_field}")
    help_padding = " " * (col_width - len(help_flag) + 2)
    lines.append(f"{help_flag}{help_padding}Show this help")
    lines.append("EOF")
    lines.append("  return")
    lines.append("}")
    lines.append("")

    # ── CLI branch ───────────────────────────────────────────────────────────
    lines.append('if [ "$#" -gt 0 ]; then')
    lines.append('  echo "\u2139\ufe0f Script called with arguments: $*" >&2')
    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        if typ == "array":
            lines.append(f"  {vname}=()")
        elif "default" not in opt:
            lines.append(f'  {vname}=""')
        else:
            rhs = shell_val(opt["default"], typ)
            lines.append(f"  {vname}={rhs}")
    lines.append('  while [ "$#" -gt 0 ]; do')
    lines.append("    case $1 in")
    for key, opt in options.items():
        vname = opt_to_var(key)
        flag = opt_to_flag(key)
        typ = opt.get("type", "string")
        lines.append(f"      {flag})")
        lines.append("        shift")
        if typ == "array":
            lines.append(f'        {vname}+=("$1")')
            lines.append(
                f'        echo "\U0001f4e9 Read argument \'{key}\': \'$1\'" >&2'
            )
        else:
            lines.append(f'        {vname}="$1"')
            lines.append(
                f'        echo "\U0001f4e9 Read argument \'{key}\': \'${{{vname}}}\'" >&2'
            )
        lines.append("        shift")
        lines.append("        ;;")
    lines.append("      -h | --help)")
    lines.append("        __usage__")
    lines.append("        exit 0")
    lines.append("        ;;")
    lines.append("      --*)")
    lines.append('        echo "\u26d4 Unknown option: \'${1}\'" >&2')
    lines.append('        exit 1')
    lines.append('        ;;')
    lines.append('      *)')
    lines.append('        echo "\u26d4 Unexpected argument: \'${1}\'" >&2')
    lines.append("        exit 1")
    lines.append("        ;;")
    lines.append("    esac")
    lines.append("  done")

    # ── env-var branch ───────────────────────────────────────────────────────
    lines.append("else")
    lines.append(
        '  echo "\u2139\ufe0f Script called with no arguments. Read environment variables." >&2'
    )
    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        if typ == "array":
            lines.append(f"  if [ \"${{{vname}+defined}}\" ]; then")
            lines.append(f"    if [ -n \"${{{vname}-}}\" ]; then")
            lines.append(
                f'      mapfile -t {vname} < <(printf \'%s\\n\' "${{{vname}}}" | grep -v \'^$\')'
            )
            lines.append(f'      for _item in "${{{vname}[@]}}"; do')
            lines.append(
                f'        echo "\U0001f4e9 Read argument \'{key}\': \'$_item\'" >&2'
            )
            lines.append("      done")
            lines.append("    else")
            lines.append(f"      {vname}=()")
            lines.append("    fi")
            lines.append("  fi")
        else:
            lines.append(
                f'  [ "${{{vname}+defined}}" ] && echo "\U0001f4e9 Read argument \'{key}\': \'${{{vname}}}\'" >&2'
            )
    lines.append("fi")
    lines.append("")

    # ── set -x ───────────────────────────────────────────────────────────────
    lines.append('[[ "${DEBUG:-}" == true ]] && set -x')
    lines.append("")

    # ── defaults ─────────────────────────────────────────────────────────────
    lines.append("# Apply defaults.")
    for key, opt in options.items():
        vname = opt_to_var(key)
        typ = opt.get("type", "string")
        if "default" not in opt:
            pass  # required — no default to apply
        elif typ == "array":
            raw_default = opt["default"]
            if raw_default == "" or raw_default is None:
                lines.append(
                    f'[ "${{{vname}+defined}}" ] || {{\n'
                    f"  {vname}=()\n"
                    f"  echo \"\u2139\ufe0f Argument '{key}' set to default value '(empty)'.\" >&2\n"
                    f"}}"
                )
            else:
                # Embed the default as an ANSI-C quoted string so newlines are preserved.
                escaped = (
                    str(raw_default)
                    .replace("\\", "\\\\")
                    .replace("'", "\\'")
                    .replace("\n", "\\n")
                    .replace("\r", "\\r")
                )
                disp = ", ".join(str(raw_default).splitlines())
                lines.append(
                    f'[ "${{{vname}+defined}}" ] || {{\n'
                    f"  mapfile -t {vname} < <(printf '%s' $'{escaped}' | grep -v '^$')\n"
                    f"  echo \"\u2139\ufe0f Argument '{key}' set to default value '{disp}'.\" >&2\n"
                    f"}}"
                )
        else:
            rhs = shell_val(opt["default"], typ)
            if typ == "boolean":
                disp = "true" if opt["default"] else "false"
            elif opt["default"] == "" or opt["default"] is None:
                disp = ""
            else:
                disp = str(opt["default"])
            lines.append(
                f'[ "${{{vname}+defined}}" ] || {{\n'
                f"  {vname}={rhs}\n"
                f"  echo \"\u2139\ufe0f Argument '{key}' set to default value '{disp}'.\" >&2\n"
                f"}}"
            )
    # ── required argument checks ─────────────────────────────────────────────
    required_opts = [
        (key, opt) for key, opt in options.items()
        if "default" not in opt
    ]
    if required_opts:
        lines.append("")
        lines.append("# Check required arguments.")
        for key, opt in required_opts:
            vname = opt_to_var(key)
            typ = opt.get("type", "string")
            if typ == "array":
                lines.append(
                    f'[ "${{#{vname}[@]}}" -eq 0 ] && {{ echo "\u26d4 Missing required argument \'{key}\'." >&2; exit 1; }}'
                )
            else:
                lines.append(
                    f'[ -z "${{{vname}}}" ] && {{ echo "\u26d4 Missing required argument \'{key}\'." >&2; exit 1; }}'
                )
    # ── enum validation ──────────────────────────────────────────────────────────
    enum_opts = [(key, opt) for key, opt in options.items() if opt.get("enum")]
    if enum_opts:
        lines.append("")
        lines.append("# Validate enum options.")
        for key, opt in enum_opts:
            vname = opt_to_var(key)
            typ = opt.get("type", "string")
            values = [str(v) for v in opt["enum"]]
            expected = ", ".join(repr(v) if v == "" else v for v in values)

            def _case_pat(v: str) -> str:
                return "''" if v == "" else v

            if typ == "array":
                # Validate each element of the array.
                pattern = " | ".join(_case_pat(v) for v in values)
                lines.append(f'for _item in "${{{vname}[@]}}"; do')
                lines.append(f"  case \"$_item\" in")
                lines.append(f"    {pattern}) ;;")
                lines.append("    *)")
                lines.append(
                    f'      echo "\u26d4 Invalid value for \'{key}\': \'$_item\' (expected: {expected})" >&2'
                )
                lines.append("      exit 1")
                lines.append("      ;;")
                lines.append("  esac")
                lines.append("done")
            else:
                pattern = " | ".join(_case_pat(v) for v in values)
                lines.append(f'case "${{{vname}}}" in')
                lines.append(f"  {pattern}) ;;")
                lines.append("  *)")
                lines.append(
                    f'    echo "\u26d4 Invalid value for \'{key}\': \'${{{vname}}}\' (expected: {expected})" >&2'
                )
                lines.append("    exit 1")
                lines.append("    ;;")
                lines.append("esac")
    # ── unexport option variables ─────────────────────────────────────────────
    # Strip the export attribute from all scalar option variables so they cannot
    # leak into child processes (e.g. third-party installers called via su/exec).
    # Array variables are never exported by bash, so they need no treatment.
    scalar_vars = [
        opt_to_var(key)
        for key, opt in options.items()
        if opt.get("type", "string") != "array"
    ]
    if scalar_vars:
        lines.append("")
        lines.append(
            "# Unexport option variables — values remain accessible in this script but"
        )
        lines.append("# are not inherited by child processes.")
        lines.append("declare +x " + " ".join(scalar_vars))

    # ── base dependencies ─────────────────────────────────────────────────────
    lines.append("")
    if dependencies and "base" in dependencies:
        lines.append(
            'ospkg__run --manifest "${_BASE_DIR}/dependencies/base.yaml" --skip_installed'
        )
        lines.append("")

    # ── end marker ────────────────────────────────────────────────────────────
    lines.append(MARKER_END)

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# shfmt post-processing
# ---------------------------------------------------------------------------


def _shfmt_format(text: str) -> str:
    """Format a bash script fragment through shfmt, respecting .editorconfig.

    Writes to a temp file in the repo root so shfmt finds the .editorconfig
    style settings.  Returns *text* unchanged if shfmt is not on PATH.
    """
    repo_root = SCRIPT_DIR.parent
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".sh",
        dir=repo_root,
        delete=False,
        encoding="utf-8",
    ) as tmp:
        tmp.write(text)
        tmp_path = Path(tmp.name)
    try:
        result = subprocess.run(
            ["shfmt", "-w", str(tmp_path)],
            capture_output=True,
            cwd=repo_root,
        )
        if result.returncode == 0:
            return tmp_path.read_text(encoding="utf-8")
        return text
    except FileNotFoundError:
        return text
    finally:
        tmp_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# File update
# ---------------------------------------------------------------------------


def write_assembled(body_path: Path, target_path: Path, new_block: str) -> tuple[bool, str]:
    """Assemble header + body and write to *target_path*.

    *body_path*   — features/<f>/install.bash  (body only, no header/marker)
    *target_path* — src/<f>/install.bash       (assembled output)

    Returns (changed, error_message).  *error_message* is empty on success.
    """
    body = body_path.read_text(encoding="utf-8").lstrip("\n")
    new_text = new_block + ("\n" + body if body else "")

    target_path.parent.mkdir(parents=True, exist_ok=True)
    current = target_path.read_text(encoding="utf-8") if target_path.exists() else None

    if new_text == current:
        return False, ""
    target_path.write_text(new_text, encoding="utf-8")
    return True, ""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    check_mode = "--check" in sys.argv

    feature_dirs = sorted(FEATURES_DIR.glob("*/metadata.yaml"))
    if not feature_dirs:
        print(f"⛔ No metadata.yaml files found under {FEATURES_DIR}", file=sys.stderr)
        return 1

    any_stale = False
    any_error = False

    for meta_path in feature_dirs:
        feature_id = meta_path.parent.name
        body_path = FEATURES_DIR / feature_id / "install.bash"
        target_path = SRC_DIR / feature_id / "install.bash"

        if not body_path.exists():
            continue

        with meta_path.open(encoding="utf-8") as fh:
            meta = yaml.safe_load(fh)

        feature_name: str = meta.get("name", feature_id)
        options: dict = meta.get("options", {})
        if not isinstance(options, dict):
            options = {}
        dependencies: dict | None = meta.get("dependencies")

        new_block = generate_block(feature_name, options, dependencies)
        new_block = _shfmt_format(new_block)

        if check_mode:
            if not target_path.exists():
                print(f"⛔ {feature_id}: assembled install.bash is missing in src/", file=sys.stderr)
                any_stale = True
                continue
            text = target_path.read_text(encoding="utf-8")
            end_pat = re.compile(r"^# END OF AUTOGENERATED BLOCK$", re.MULTILINE)
            m_end = end_pat.search(text)
            if m_end is None:
                print(
                    f"⛔ {feature_id}: '{MARKER_END}' marker missing in src/",
                    file=sys.stderr,
                )
                any_stale = True
                continue
            # Compare from file start to end of marker line (including its \n)
            current_block = text[: m_end.end() + 1]
            if current_block != new_block:
                print(f"⛔ {feature_id}: generated header is stale", file=sys.stderr)
                any_stale = True
            else:
                print(f"✅ {feature_id}: in sync", file=sys.stderr)
        else:
            changed, err = write_assembled(body_path, target_path, new_block)
            if err:
                print(f"⛔ {feature_id}: {err}", file=sys.stderr)
                any_error = True
            elif changed:
                print(f"✅ {feature_id}: assembled install.bash written", file=sys.stderr)
            else:
                print(f"✅ {feature_id}: install.bash unchanged", file=sys.stderr)

    if check_mode and any_stale:
        print("", file=sys.stderr)
        print(
            "⛔ Stale generated headers detected. Run: bash sync-lib.sh",
            file=sys.stderr,
        )
        return 1

    if any_error:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
