#!/usr/bin/env bash

set -euo pipefail

_SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
_BASE_DIR="$(cd "$_SELF_DIR/.." && pwd)"

# shellcheck source=lib/ospkg.sh
. "$_SELF_DIR/_lib/ospkg.sh"
# shellcheck source=lib/logging.sh
. "$_SELF_DIR/_lib/logging.sh"

logging__setup
trap 'logging__cleanup' EXIT

if [ "$#" -gt 0 ]; then
  NERD_FONTS=""
  FONT_URLS=""
  GH_RELEASE_FONTS=""
  FONT_DIR=""
  P10K_FONTS=""
  OVERWRITE=""
  DEBUG=""
  LOGFILE=""

  while [[ $# -gt 0 ]]; do
    case $1 in
      --nerd_fonts)
        shift
        NERD_FONTS="$1"
        shift
        ;;
      --font_urls)
        shift
        FONT_URLS="$1"
        shift
        ;;
      --gh_release_fonts)
        shift
        GH_RELEASE_FONTS="$1"
        shift
        ;;
      --font_dir)
        shift
        FONT_DIR="$1"
        shift
        ;;
      --p10k_fonts)
        shift
        P10K_FONTS="$1"
        shift
        ;;
      --overwrite)
        OVERWRITE=true
        shift
        ;;
      --debug)
        DEBUG=true
        shift
        ;;
      --logfile)
        shift
        LOGFILE="$1"
        shift
        ;;
      --help | -h) __usage__ ;;
      --*)
        echo "⛔ Unknown option: '${1}'" >&2
        exit 1
        ;;
      *)
        echo "⛔ Unexpected argument: '${1}'" >&2
        exit 1
        ;;
    esac
  done
fi

: "${NERD_FONTS=Meslo,JetBrainsMono}"
: "${FONT_URLS=}"
: "${GH_RELEASE_FONTS=}"
: "${FONT_DIR=}" # empty → auto-detect below
: "${P10K_FONTS:=false}"
: "${OVERWRITE:=false}"
: "${DEBUG:=false}"
: "${LOGFILE=}"

[[ "${DEBUG:-}" == true ]] && set -x

ospkg__run --manifest "${_BASE_DIR}/dependencies/base.yaml" --skip_installed

# END OF AUTOGENERATED BLOCK

# Auto-detect font directory when not explicitly set.
if [[ -z "$FONT_DIR" ]]; then
  FONT_DIR="$(os__font_dir)"
fi

_FONT_ARGS=(--font_dir "$FONT_DIR")
[ -n "$NERD_FONTS" ] && _FONT_ARGS+=(--nerd_fonts "$NERD_FONTS")
[ -n "$FONT_URLS" ] && _FONT_ARGS+=(--font_urls "$FONT_URLS")
[ -n "$GH_RELEASE_FONTS" ] && _FONT_ARGS+=(--gh_release_fonts "$GH_RELEASE_FONTS")
[[ "$P10K_FONTS" == true ]] && _FONT_ARGS+=(--p10k_fonts)
[[ "$OVERWRITE" == true ]] && _FONT_ARGS+=(--overwrite)
[[ "$DEBUG" == true ]] && _FONT_ARGS+=(--debug)

bash "$_SELF_DIR/install_fonts.sh" "${_FONT_ARGS[@]}"
