# --- Powerlevel10k instant prompt --------------------------------------- #
# Must be sourced at the very top of zshrc, before any output or slow     #
# initialisation, to enable the instant-prompt feature.  Skipped if the   #
# cache file does not yet exist (first login before p10k configure runs). #
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# --- oh-my-zsh ---------------------------------------------------------- #
# Configure oh-my-zsh before sourcing it.  All ZSH_* variables and the   #
# plugins array must be set prior to sourcing oh-my-zsh.sh.              #
export ZSH="/usr/local/share/oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
    git
    github
    per-directory-history
    pip
    python
    z
    zsh-syntax-highlighting
)
ZSH_CUSTOM="$ZSH/custom"
ZSH_CACHE_DIR="$ZSH/cache"
# Disable automatic update prompts (updates are managed by the image build).
zstyle ':omz:update' mode disabled
# Use a shared compdump file inside the oh-my-zsh cache directory.
ZSH_COMPDUMP="$ZSH_CACHE_DIR/.zcompdump"
# Show a coloured waiting indicator while async completions are loading.
COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
CASE_SENSITIVE="true"
ENABLE_CORRECTION=true
# Display history timestamps in yyyy-mm-dd format.
HIST_STAMPS="yyyy-mm-dd"
source "$ZSH/oh-my-zsh.sh"

# --- Shared user interactive config ------------------------------------- #
# Source ~/.shellrc for POSIX-compatible aliases and functions shared with  #
# bash.  Sourced after oh-my-zsh so user config can override framework     #
# defaults.                                                                 #
[ -f "$HOME/.shellrc" ] && . "$HOME/.shellrc"

# --- Terminal title (Powerlevel10k overrides) --------------------------- #
# Set the default idle title strings; p10k may override these at runtime. #
ZSH_THEME_TERM_TITLE_IDLE="%n@%m:%~"
ZSH_THEME_TERM_TAB_TITLE_IDLE="%15<..<%~%<<"

# --- Powerlevel10k theme ------------------------------------------------ #
# Source the p10k configuration (generated by `p10k configure`).          #
. "/etc/zsh/p10k.zsh"
