name: Lint

on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true

jobs:

  json-schema:
    name: Schema Validation
    if: fromJSON(inputs.config).validate.enabled == true
    runs-on: ubuntu-latest
    container:
      image: ${{ fromJSON(inputs.config).ci_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download Source Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ fromJSON(inputs.config).artifact_src_name }}
          path: ${{ fromJSON(inputs.config).artifact_src_path }}

      - name: Validate Feature Metadata
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          validate-only: "true"
          base-path-to-features: ${{ fromJSON(inputs.config).validate.features_path }}

      - name: Validate Feature Test Definitions
        run: pixi run --environment test proman-validate-tests

  lint-shell:
    name: Shell Scripts
    if: fromJSON(inputs.config).shell.enabled == true
    runs-on: ubuntu-latest
    container:
      image: ${{ fromJSON(inputs.config).ci_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Download Source Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ fromJSON(inputs.config).artifact_src_name }}
          path: ${{ fromJSON(inputs.config).artifact_src_path }}

      - name: Check Formatting
        run: just format-sh-check

      - name: Lint
        if: "!cancelled()"
        run: just lint-sh-check

  lint-python:
    name: Python
    if: fromJSON(inputs.config).python.enabled == true
    runs-on: ubuntu-latest
    container:
      image: ${{ fromJSON(inputs.config).ci_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check Formatting
        run: just format-py-check

      - name: Lint
        if: "!cancelled()"
        run: just lint-py-check
