name: Test Development

on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true

jobs:

  test-dev:
    name: Development
    if: fromJSON(inputs.config).enabled == true
    runs-on: ubuntu-latest
    container:
      image: ${{ fromJSON(inputs.config).ci_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Test
        if: "!cancelled()"
        run: just test-py
